services:
  truckstop-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5244:8080"
      - "7244:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - truckstop-network

  truckstop-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - truckstop-network
    depends_on:
      - truckstop-api

networks:
  truckstop-network:
    driver: bridge
